### ISSUE TITLE
分割肿瘤

### ISSUE THREAD

**Issue by ZZL0816** [Cooper111/3Dircadb_Use_Unet#3]
请问这个可以分割出肿瘤吗，我只能把肝脏分割出来，不知道是哪里出了问题，可以指教一下吗

**Comment by Cooper111** [comment]
你好，按理说能分割出肿瘤，以真值图的形式输出的···但我现在转java开发了，貌似帮不了你了:(
你可以参照下原博和以下数据集，看一下代码问题：
- DRIVE
- ISBI
- LiTS
- data-science-bowl-2018

**Comment by Brisk-sudo** [comment]
你好，请问你用这个代码实现分割肿瘤了吗，我也是运行出来只能分割肝脏
